document.write('this is math section');
var a=-2;
document.write(2*(2+7));
document.write(3%2);
document.write(Math.abs(a));
document.write(Math.max(-10,a,10));
document.write(Math.min(-10,a,10));
document.write(Math.pow(a,3));
document.write(Math.sqrt(9));
document.write(Math.round(4.5));
document.write(Math.ceil(4.5));
document.write(Math.floor(4.5));
document.write(Math.random() * 10);