document.write(" yoooo is ya boi ksi");
var phrase=' yoooo is ya boi ksi';
var text=" boi";
document.write(phrase.length);
document.write(phrase.toUpperCase());
document.write(phrase.toLowerCase());
document.write(phrase.charAt(0));
document.write(phrase.indexOf('s'));
document.write(phrase.lastIndexOf('s'));
document.write(phrase.substring(0,5));
document.write(phrase.substring(phrase.indexOf('s'),12).toUpperCase());
document.write(phrase.endsWith('asi'));
document.write(phrase.includes('i ks'));
document.write(phrase.includes(text));
document.write(phrase.replace('boi','boy'));
document.write(phrase + ' heheeheh' + text);